#!/bin/bash

# ProofPlay Deployment Script
# Deploys ProofPlay smart contracts to Sui testnet

set -e  # Exit on error

echo "╔════════════════════════════════════════════════════════════╗"
echo "║                                                            ║"
echo "║            🚀 PROOFPLAY DEPLOYMENT SCRIPT 🚀               ║"
echo "║                                                            ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print section headers
print_section() {
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "  $1"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
}

# Check prerequisites
check_prerequisites() {
    print_section "🔍 Checking Prerequisites"

    # Check Sui CLI
    if ! command -v sui &> /dev/null; then
        echo -e "${RED}❌ Sui CLI not found${NC}"
        exit 1
    fi
    echo -e "${GREEN}✅ Sui CLI found${NC}"

    # Check if Move contracts are built
    if [ ! -d "move/build" ]; then
        echo -e "${YELLOW}⚠️  Move contracts not built. Building now...${NC}"
        cd move
        sui move build
        cd ..
    fi
    echo -e "${GREEN}✅ Move contracts ready${NC}"

    # Check active address
    ACTIVE_ADDRESS=$(sui client active-address 2>&1)
    if [ $? -ne 0 ]; then
        echo -e "${RED}❌ No active Sui address${NC}"
        echo "   Run: sui client new-address ed25519"
        exit 1
    fi
    echo -e "${GREEN}✅ Active address: ${ACTIVE_ADDRESS}${NC}"

    # Check gas balance
    echo "Checking gas balance..."
    sui client gas --json > /tmp/gas.json 2>&1 || true

    if [ -s /tmp/gas.json ]; then
        echo -e "${GREEN}✅ Gas available${NC}"
    else
        echo -e "${YELLOW}⚠️  Low gas. Getting testnet tokens...${NC}"
        sui client faucet || echo -e "${YELLOW}   Manual faucet may be needed${NC}"
    fi
}

# Deploy contracts
deploy_contracts() {
    print_section "📦 Deploying Smart Contracts to Sui Testnet"

    cd move

    echo "Publishing package..."
    echo ""

    # Publish with explicit gas budget
    DEPLOY_OUTPUT=$(sui client publish --gas-budget 100000000 --json)

    if [ $? -eq 0 ]; then
        echo -e "${GREEN}✅ Deployment successful!${NC}"
        echo ""

        # Extract package ID
        PACKAGE_ID=$(echo "$DEPLOY_OUTPUT" | grep -o '"packageId":"[^"]*' | cut -d'"' -f4 | head -1)

        if [ ! -z "$PACKAGE_ID" ]; then
            echo -e "${BLUE}📦 Package ID: ${PACKAGE_ID}${NC}"
            echo "$PACKAGE_ID" > ../deployed-package-id.txt
            echo ""
            echo "Package ID saved to: deployed-package-id.txt"
        fi

        # Extract transaction digest
        TX_DIGEST=$(echo "$DEPLOY_OUTPUT" | grep -o '"digest":"[^"]*' | cut -d'"' -f4 | head -1)
        if [ ! -z "$TX_DIGEST" ]; then
            echo -e "${BLUE}🔗 Transaction: ${TX_DIGEST}${NC}"
            echo ""
            echo "View on explorer:"
            echo "https://suiscan.xyz/testnet/tx/${TX_DIGEST}"
        fi

    else
        echo -e "${RED}❌ Deployment failed${NC}"
        cd ..
        exit 1
    fi

    cd ..
}

# Create .env file
create_env() {
    print_section "⚙️  Creating Environment Configuration"

    if [ -f "deployed-package-id.txt" ]; then
        PACKAGE_ID=$(cat deployed-package-id.txt)

        cat > .env << EOF
# ProofPlay Environment Configuration
# Generated by deploy.sh on $(date)

# Sui Configuration
SUI_NETWORK=testnet
SUI_PACKAGE_ID=${PACKAGE_ID}
SUI_ACTIVE_ADDRESS=$(sui client active-address)

# Walrus Configuration
WALRUS_PUBLISHER_URL=https://publisher.walrus-testnet.walrus.space
WALRUS_AGGREGATOR_URL=https://aggregator.walrus-testnet.walrus.space

# API Configuration
API_PORT=3000
NODE_ENV=development
EOF

        echo -e "${GREEN}✅ Environment configuration created: .env${NC}"
        echo ""
        echo "Configuration:"
        cat .env
    fi
}

# Display next steps
show_next_steps() {
    print_section "✅ Deployment Complete!"

    echo ""
    echo "Next steps:"
    echo ""
    echo "  1️⃣  Test the deployment:"
    echo "     sui client object $(cat deployed-package-id.txt)"
    echo ""
    echo "  2️⃣  Run the demo:"
    echo "     cd game-sdk && npm run demo"
    echo ""
    echo "  3️⃣  Start the API:"
    echo "     cd api && npm run dev"
    echo ""
    echo "  4️⃣  Open the frontend:"
    echo "     cd client && open index.html"
    echo ""
    echo "  5️⃣  View on explorer:"
    echo "     https://suiscan.xyz/testnet/object/$(cat deployed-package-id.txt)"
    echo ""
}

# Main execution
main() {
    # Navigate to project root
    cd "$(dirname "$0")/.."

    check_prerequisites
    deploy_contracts
    create_env
    show_next_steps
}

# Run main function
main
